version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  my-job:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - snyk/scan
      - run:
          name: Install dependencies
          command: npm install -q
      - run:
          name: Run tests
          command: npm test

workflows:
  my-workflow:
    jobs:
      - my-job:
        context:
          - mao
