version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  my-job:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan:
        project: ${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}

workflows:
  my-workflow:
    jobs:
      - my-job
